### ISSUE TITLE
Signaling on-screen error / issues during simulations

### ISSUE THREAD

**Issue by julian-molina** [Superalgos/Releases#2]
Handled errors / events are currently shown with a red circle on the Designer element related to the issue.

![image](https://user-images.githubusercontent.com/13994516/63210146-d5998880-c0ea-11e9-8cdb-80ea7432b494.png)

At times, it may be hard to notice such markings on the Designer, as not all elements show on screen all the time.

I believe a more prominent on-screen notice that something went wrong would help troubleshoot these cases easier. Maybe a pop up window or a sign rendered over the charts.

**Comment by Luis-Fernando-Molina** [comment]
The proposed solution would pop up windows for any error that many times does not need the attention of the user. The rationale is that is you believe something is not working, you scan your work-space to see if there are errors at the areas you are working on. 

A window for every possible error at all times would be annoying.

**Comment by julian-molina** [comment]
It doesn't need to warn about all possible errors. It should warn of the same kind of situations that would currently be signaled in the Designer.

From the user stand point, errors are never expected. When you work on a strategy and something seems of, you normally invest time carefully looking into the outcome of the strategy before thinking of checking for errors on the Designer. If an error happened, that time goes to waste.

The signaling of errors that affect the results of simulations or live trading should be more prominent.

**Comment by Luis-Fernando-Molina** [comment]
Make an exact proposal, that does not includes pop ups.

**Comment by Luis-Fernando-Molina** [comment]
I need to use the issue tracker to organize my work efficiently. For that reason I will close this issue until you come up with a cool specific idea that can be implemented. At that point we can re open it.
