### ISSUE TITLE
Line relating placed and filled orders on trading simulation layer

### ISSUE THREAD

**Issue by julian-molina** [Superalgos/Releases#3]
The line joining triangles signalling the relationship between placed and filled orders may prevent users from seeing the upper tail of the candle (candle.max).

![image](https://user-images.githubusercontent.com/13994516/63210204-c6670a80-c0eb-11e9-8948-b5c33e7310ec.png)

Maybe a dotted line instead of a solid line would be better.

**Comment by Luis-Fernando-Molina** [comment]
Done, you will see it at the next release
