### ISSUE TITLE
On-screen error doesn't show when tab is fully closed

### ISSUE THREAD

**Issue by julian-molina** [Superalgos/Releases#6]
On-screen warnings or errors shown in the Designer may disappear when the tab is fully closed, as shown in the GIF below.

![Error](https://user-images.githubusercontent.com/13994516/63213579-528a2980-c10e-11e9-8464-76cb4b369db4.gif)

**Comment by Luis-Fernando-Molina** [comment]
Yes, that is a consequence of the errors being sent to the Designer by the panels. When you close the charts the panels are deactivated and thus, the errors dissapear. Since there is no other way of getting rid of the errors as of today, i would leave it like that for now.

**Comment by julian-molina** [comment]
Will document accordingly and change the BUG label to an IMPROVEMENT label.

**Comment by Luis-Fernando-Molina** [comment]
I really do not have plans to change this behavior, unless you come with an specific implementation idea that would be really nice. When you do, we can reopen the issue.
