### ISSUE TITLE
Ticker variables are broken, showing constant values

### ISSUE THREAD

**Issue by julian-molina** [Superalgos/Releases#8]
When I use ```ticker``` as the formula for Position Rate, I get a simulation that seems accurate:

![image](https://user-images.githubusercontent.com/13994516/63223515-1068f280-c1b7-11e9-8036-31036427fea2.png)

However, when I use an actual variable, like ```ticker.last``` the simulation draws the Take Position line in an incorrect position:

![image](https://user-images.githubusercontent.com/13994516/63223531-473f0880-c1b7-11e9-8d47-d671ba62e7bf.png)

A similar thing happens when I use arithmetic operations on more than one of the ticker variables, such as in ```ticker.ask-(ticker.ask-ticker.bid)*0.2```:

![image](https://user-images.githubusercontent.com/13994516/63223541-6e95d580-c1b7-11e9-9634-701c15a9636a.png)

I did a a few tests:

1. I set ```ticker.last + 1000``` as a take profit formula, just to be able to see the value of ```ticker.last```. The variable ```ticker.last``` seems to have a fixed value for long periods of time (if not always). The value is 10357.71

![Test](https://user-images.githubusercontent.com/13994516/63223621-e284ad80-c1b8-11e9-946f-8c3223370366.gif)

I did a similar test with ```ticker.bid``` and the same thing happens. The value for ```ticker.bid``` is 10398.38, and seems to be constant, even when the market was at 13K +:

![Test](https://user-images.githubusercontent.com/13994516/63223668-c46b7d00-c1b9-11e9-83e2-6eecf6fdefd0.gif)

**Comment by Luis-Fernando-Molina** [comment]
Fixed at latest release
